from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4

import datetime
import os


def generate_pdf_report(image_path, results):

    os.makedirs("outputs/report", exist_ok=True)

    output_file = "outputs/report/dr_report.pdf"

    styles = getSampleStyleSheet()

    story = []

    story.append(Paragraph("Diabetic Retinopathy AI Analysis Report", styles['Title']))

    story.append(Spacer(1,20))

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    story.append(Paragraph(f"Timestamp: {timestamp}", styles['Normal']))
    story.append(Paragraph(f"Prediction: {results['prediction']}", styles['Normal']))

    story.append(Spacer(1,20))

    story.append(Paragraph("Uploaded Retina Image", styles['Heading2']))
    story.append(Image(image_path, width=400, height=300))

    story.append(Spacer(1,20))

    story.append(Paragraph("GradCAM Heatmap", styles['Heading2']))
    story.append(Image(results["gradcam_heatmap"], width=400, height=300))

    story.append(Spacer(1,20))

    story.append(Paragraph("Evidence Map", styles['Heading2']))
    story.append(Image(results["evidence_map"], width=400, height=300))

    story.append(Spacer(1,20))

    story.append(Paragraph("Consistency Visualization", styles['Heading2']))
    story.append(Image(results["consistency_image"], width=400, height=300))

    story.append(Spacer(1,20))

    story.append(Paragraph("Region Importance Map", styles['Heading2']))
    story.append(Image(results["region_map"], width=400, height=300))

    story.append(Spacer(1,20))

    story.append(Paragraph("Saliency Evolution Map", styles['Heading2']))
    story.append(Image(results["saliency_map"], width=400, height=300))

    story.append(Spacer(1,30))

    story.append(Paragraph(
        "Disclaimer: This report is generated by an AI decision-support system and "
        "should not replace professional medical diagnosis.",
        styles['Italic']
    ))

    doc = SimpleDocTemplate(output_file, pagesize=A4)

    doc.build(story)

    return output_file